### ISSUE TITLE
Parsing error on simple Dictionary type

### ISSUE THREAD

**Issue by razcore-rad** [Beliaar/godot-yaml#4]
so I tried something simple:
```yaml
position:
  x: 1
  y: 2
  z: 3
```
which returns: `{position:{True:2, x:1, z:3}}`, don't know what that `True` is all about, but it seems it doesn't like `y`.
