### ISSUE TITLE
Make parsing more robust for !<Godot/TYPE>

### ISSUE THREAD

**Issue by razcore-rad** [Beliaar/godot-yaml#5]
As I suggested in the PR review comment, there's a problem if these `!<Godot/...>` comments that are wrong. So, in the case someone wants to write YAML by hand (cause why not, it can be done), at the moment something like:
```yaml
position: !<Godot/>
  x: 0
  y: 0
```
closes the app unexpectedly, while something like this:
```yaml
position: !<Godot/Variant/Vector2/Test>
  x: 0
  y: 0
```
doesn't give any warning/errors.
